version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: tickets-mariadb
      working_dir: /application
      volumes:
        - .:/application
        - ../mariadb:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=passwordforroot
        - MYSQL_DATABASE=tickets
        - MYSQL_USER=databaseuser
        - MYSQL_PASSWORD=databasepassword
      ports:
        - "8084:3306"

    webserver:
      image: nginx:alpine
      container_name: tickets-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: tickets-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

